"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from './components/navbar'
import Footer from './components/footer'
import { SessionProvider } from 'next-auth/react';
import { createContext, useState, useEffect} from 'react'

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export const LoginContext = createContext()


export default function RootLayout({ children }) {
const [signIn, setSignIn] = useState()

useEffect(()=> {
  console.log(signIn)
},[signIn])

  return (
    <LoginContext.Provider value={{signIn, setSignIn}}>
      <SessionProvider>
        <html lang="en">
          <body className={inter.className}><Navbar />{children}<Footer /></body>
        </html>
      </SessionProvider>
    </LoginContext.Provider>
  )
}
